# Generated by Django 5.0.6 on 2024-08-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='adress',
        ),
    ]
