# Generated by Django 5.0.6 on 2024-08-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0002_remove_employee_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='can_edit_employee',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='can_edit_projects',
            new_name='super_admin',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='can_edit_users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_employee',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_projects',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_users',
        ),
        migrations.RemoveField(
            model_name='role',
            name='full_access',
        ),
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.DeleteModel(
            name='UserEmployeeMapping',
        ),
    ]
