# Generated by Django 5.0.6 on 2024-08-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0003_delete_invoice_delete_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='admin',
            new_name='full_access',
        ),
    ]
