# Generated by Django 5.0.6 on 2024-06-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_leaverequest_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeLeaveAllocation',
        ),
    ]
