# Generated by Django 5.0.6 on 2024-06-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_delete_employeeleaveallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='duration',
        ),
    ]
