# Generated by Django 5.0.6 on 2024-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_remove_leaverequest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
