# Generated by Django 5.0.6 on 2024-06-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_leaverequest_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='duration',
        ),
    ]
