# Generated by Django 5.0.6 on 2024-06-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
