# Generated by Django 5.0.6 on 2024-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compansation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.CharField(default=0, max_length=25)),
                ('compansation', models.TextField(default='', max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='remaining_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
