# Generated by Django 5.0.6 on 2024-07-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_compansation_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='compansation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
