# Generated by Django 5.0.6 on 2024-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0016_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='assign_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
