# Generated by Django 5.0.6 on 2024-07-24 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0017_leavetype_assign_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='used_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
