# Generated by Django 5.0.6 on 2024-07-28 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0018_leaverequest_used_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compansation',
            name='compansation',
        ),
        migrations.RemoveField(
            model_name='compansation',
            name='number_of_days',
        ),
        migrations.AddField(
            model_name='compansation',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compansation',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='compansation',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.leavetype'),
        ),
        migrations.AddField(
            model_name='compansation',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compansation',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='compansation',
            name='used_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
