# Generated by Django 5.0.6 on 2024-07-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0019_remove_compansation_compansation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(max_length=225),
        ),
    ]
