# Generated by Django 5.0.6 on 2024-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0020_alter_leaverequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(default='', max_length=225),
        ),
    ]
