# Generated by Django 5.0.6 on 2024-08-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0025_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compansation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
