# Generated by Django 5.0.6 on 2024-08-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0027_carryforwardpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_compensation_days', models.IntegerField(default=60)),
            ],
        ),
    ]
