# Generated by Django 5.0.6 on 2024-08-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0028_compensationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='locked_days',
            field=models.IntegerField(default=0),
        ),
    ]
