# Generated by Django 5.0.6 on 2024-08-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0029_leavebalance_locked_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='compansation',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
