# Generated by Django 5.0.6 on 2024-08-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0031_alter_compansation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='description',
        ),
    ]
